export const AlgDB = [
  // F2L STARTS HERE --------------------------------------------------------------------------------------
  {
    alg_id: "F2L_1",
    alg_cat: "F2L",
    algcat_id: 1,
    image: "/alg_images/F2L_1.png",
    steps1: "U R U' R'",
    steps2: "R' F R F'",
    steps3: "y' r' U' R U M'",
    steps4: "y U F' L F L2 U L",
    description: "Free Pairs",
  },
  {
    alg_id: "F2L_2",
    alg_cat: "F2L",
    algcat_id: 2,
    image: "/alg_images/F2L_2.png",
    steps1: "F R' F' R",
    steps2: "y' U' R' U R",
    steps3: "U' F' U F",
    steps4: "y U' L' U L",
    description: "Free Pairs",
  },
  {
    alg_id: "F2L_3",
    alg_cat: "F2L",
    algcat_id: 3,
    image: "/alg_images/F2L_3.png",
    steps1: "F' U' F",
    steps2: "y' R' U' R",
    steps3: "y L' U' L",
    steps4: "S U R U' R' S'",
    description: "Free Pairs",
  },
  {
    alg_id: "F2L_4",
    alg_cat: "F2L",
    algcat_id: 4,
    image: "/alg_images/F2L_4.png",
    steps1: "R U R'",
    steps2: "y' f R f'",
    steps3: "y F U F'",
    steps4: "y2 L U L'",
    description: "Free Pairs",
  },
  {
    alg_id: "F2L_5",
    alg_cat: "F2L",
    algcat_id: 5,
    image: "/alg_images/F2L_5.png",
    steps1: "U' R U R' U2 R U' R'",
    steps2: "F2 L' U' L U F2",
    steps3: "U' R U R' U' R U2 R'",
    steps4: "U' R U R' U R' F R F'",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_6",
    alg_cat: "F2L",
    algcat_id: 6,
    image: "/alg_images/F2L_6.png",
    steps1: "U' r U' R' U R U r'",
    steps2: "y' U R' U' R U2 R' U R",
    steps3: "d R' U' R U2 R' U R",
    steps4: "U F' U' F U2 F' U F",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_7",
    alg_cat: "F2L",
    algcat_id: 7,
    image: "/alg_images/F2L_7.png",
    steps1: "U' R U2 R' U' R U2 R'",
    steps2: "M' U' M U2 r U' r'",
    steps3: "U' R U2 R' U R' F R F'",
    steps4: "U' R U2 R' U2 R U' R'",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_8",
    alg_cat: "F2L",
    algcat_id: 8,
    image: "/alg_images/F2L_8.png",
    steps1: "d R' U2 R U R' U2 R",
    steps2: "r' U2 R2 U R2 U r",
    steps3: "y' U R' U2 R U2 R' U R",
    steps4: "y U L' U2 L U2 L' U L",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_9",
    alg_cat: "F2L",
    algcat_id: 9,
    image: "/alg_images/F2L_9.png",
    steps1: "U' R U' R' U F' U' F",
    steps2: "F R U R' U' F' R U' R'",
    steps3: "U' R U' R' d R' U' R",
    steps4: "d R' U' R U' R' U' R",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_10",
    alg_cat: "F2L",
    algcat_id: 10,
    image: "/alg_images/F2L_10.png",
    steps1: "U' R U R' U R U R'",
    steps2: "U2 R U' R' U' R U R'",
    steps3: "y' U R' U R U' f R f'",
    steps4: "d R' U R d' R U R'",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_11",
    alg_cat: "F2L",
    algcat_id: 11,
    image: "/alg_images/F2L_11.png",
    steps1: "U' R U2 R' U F' U' F",
    steps2: "y' R U2 R2 U' R2 U' R'",
    steps3: "U' R U2 R' d R' U' R",
    steps4: "F' U L' U2 L U2 F",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_12",
    alg_cat: "F2L",
    algcat_id: 12,
    image: "/alg_images/F2L_12.png",
    steps1: "R U' R' U R U' R' U2 R U' R'",
    steps2: "R' U2 R2 U R2 U R",
    steps3: "U R U' R' U' R U R' U' R U R'",
    steps4: "R' D' R U2 R' D R2 U R'",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_13",
    alg_cat: "F2L",
    algcat_id: 13,
    image: "/alg_images/F2L_13.png",
    steps1: "y' U R' U R U' R' U' R",
    steps2: "M' U' R U R' U2 R U' r'",
    steps3: "R U' R' U R' F R F' R U' R'",
    steps4: "d R' U R U' R' U' R",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_14",
    alg_cat: "F2L",
    algcat_id: 14,
    image: "/alg_images/F2L_14.png",
    steps1: "U' R U' R' U R U R'",
    steps2: "R U2 R' U2 R U R' U2 R U' R'",
    steps3: "U' R2 D R' U R D' R2",
    steps4: "U2 R2 U R' U R U2 R2",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_15",
    alg_cat: "F2L",
    algcat_id: 15,
    image: "/alg_images/F2L_15.png",
    steps1: "R' D' R U' R' D R U R U' R'",
    steps2: "R U R' U2 R U' R' U R U' R'",
    steps3: "M U r U' r' U' M'",
    steps4: "F' U F U2 R U R'",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_16",
    alg_cat: "F2L",
    algcat_id: 16,
    image: "/alg_images/F2L_16.png",
    steps1: "R U' R' U2 F' U' F",
    steps2: "R U' R' U2 y' R' U' R",
    steps3: "U M' U R U' r' U' R U R'",
    steps4: "U F U R U' R' F' R U R'",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_17",
    alg_cat: "F2L",
    algcat_id: 17,
    image: "/alg_images/F2L_17.png",
    steps1: "R U2 R' U' R U R'",
    steps2: "y2 L U2 L' U' L U L'",
    steps3: "R U R' U' R U2 R' U2 R U R'",
    steps4: "y L F' L' F L' U L U' L' U L",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_18",
    alg_cat: "F2L",
    algcat_id: 18,
    image: "/alg_images/F2L_18.png",
    steps1: "y' R' U2 R U R' U' R",
    steps2: "R' F R F' R U' R' U R U' R'",
    steps3: "y L' U2 L U L' U' L",
    steps4: "F' U2 F U F' U' F",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_19",
    alg_cat: "F2L",
    algcat_id: 19,
    image: "/alg_images/F2L_19.png",
    steps1: "U R U2 R' U R U' R'",
    steps2: "U R U2 R2 F R F'",
    steps3: "d f R2 f' U f R' f'",
    steps4: "R U' R' U R U' R' U R U R'",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_20",
    alg_cat: "F2L",
    algcat_id: 20,
    image: "/alg_images/F2L_20.png",
    steps1: "y' U' R' U2 R U' R' U R",
    steps2: "U' R U' R2 F R F' R U' R'",
    steps3: "y U' L' U2 L U' L' U L",
    steps4: "d' L' U2 L U' L' U L",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_21",
    alg_cat: "F2L",
    algcat_id: 21,
    image: "/alg_images/F2L_21.png",
    steps1: "U2 R U R' U R U' R'",
    steps2: "R U' R' U2 R U R'",
    steps3: "R B U2 B' R'",
    steps4: "y' f R' f' U2 f R f'",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_22",
    alg_cat: "F2L",
    algcat_id: 22,
    image: "/alg_images/F2L_22.png",
    steps1: "r U' r' U2 r U r'",
    steps2: "F' L' U2 L F",
    steps3: "y' U2 R' U' R U' R' U R",
    steps4: "y U2 L' U' L U' L' U L",
    description: "Disconnected Pairs",
  },
  {
    alg_id: "F2L_23",
    alg_cat: "F2L",
    algcat_id: 23,
    image: "/alg_images/F2L_23.png",
    steps1: "U R U' R' U' R U' R' U R U' R'",
    steps2: "R U R' U2 R U R' U' R U R'",
    steps3: "U2 R2 U2 R' U' R U' R2",
    steps4: "R U' R2 D' R U2 R' D R",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_24",
    alg_cat: "F2L",
    algcat_id: 24,
    image: "/alg_images/F2L_24.png",
    steps1: "F U R U' R' F' R U' R'",
    steps2: "U' R U R2 F R F' R U' R'",
    steps3: "y' R' U' R U2 R' U' R U R' U' R",
    steps4: "y U' L' U L U L' U L U' L' U L",
    description: "Connected Pairs",
  },
  {
    alg_id: "F2L_25",
    alg_cat: "F2L",
    algcat_id: 25,
    image: "/alg_images/F2L_25.png",
    steps1: "U' R' F R F' R U R'",
    steps2: "R' F' R U R U' R' F",
    steps3: "U' F' R U R' U' R' F R",
    steps4: "U' F' U F U R U' R'",
    description: "Corner In Slot",
  },
  {
    alg_id: "F2L_26",
    alg_cat: "F2L",
    algcat_id: 26,
    image: "/alg_images/F2L_26.png",
    steps1: "U R U' R' F R' F' R",
    steps2: "R S' R' U R S R'",
    steps3: "U R U R' U' y L' U' L",
    steps4: "y' R U R U R U' R' U' R'",
    description: "Corner In Slot",
  },
  {
    alg_id: "F2L_27",
    alg_cat: "F2L",
    algcat_id: 27,
    image: "/alg_images/F2L_27.png",
    steps1: "R U' R' U R U' R'",
    steps2: "F' U' F U2 R U' R'",
    steps3: "y' f R' f' U f R' f'",
    steps4: "y' f R' f' r' U' R U M'",
    description: "Corner In Slot",
  },
  {
    alg_id: "F2L_28",
    alg_cat: "F2L",
    algcat_id: 28,
    image: "/alg_images/F2L_28.png",
    steps1: "R U R' U' F R' F' R",
    steps2: "y L' U L U' L' U L",
    steps3: "F' U F U' F' U F",
    steps4: "y' R' U R U' R' U R",
    description: "Corner In Slot",
  },
  {
    alg_id: "F2L_29",
    alg_cat: "F2L",
    algcat_id: 29,
    image: "/alg_images/F2L_29.png",
    steps1: "R' F R F' U R U' R'",
    steps2: "y' R' U' R U R' U' R",
    steps3: "y L' U' L U L' U' L",
    steps4: "R' F R F' R' F R F'",
    description: "Corner In Slot",
  },
  {
    alg_id: "F2L_30",
    alg_cat: "F2L",
    algcat_id: 30,
    image: "/alg_images/F2L_30.png",
    steps1: "R U R' U' R U R'",
    steps2: "U' F R' F' R2 U R'",
    steps3: "U' R U2 R' U2 R U R'",
    steps4: "U2 F' U F R U R'",
    description: "Corner In Slot",
  },
  {
    alg_id: "F2L_31",
    alg_cat: "F2L",
    algcat_id: 31,
    image: "/alg_images/F2L_31.png",
    steps1: "U' R' F R F' R U' R'",
    steps2: "R U' R' U y' R' U R",
    steps3: "F' U F R U2 R'",
    steps4: "R U' R' U2 F R' F' R",
    description: "Edge In Slot",
  },
  {
    alg_id: "F2L_32",
    alg_cat: "F2L",
    algcat_id: 32,
    image: "/alg_images/F2L_32.png",
    steps1: "U R U' R' U R U' R' U R U' R'",
    steps2: "R U R' U' R U R' U' R U R'",
    steps3: "R2 U R2 U R2 U2 R2",
    steps4: "U' F R' F' R U' R U R'",
    description: "Edge In Slot",
  },
  {
    alg_id: "F2L_33",
    alg_cat: "F2L",
    algcat_id: 33,
    image: "/alg_images/F2L_33.png",
    steps1: "U' R U' R' U2 R U' R'",
    steps2: "R U R' U' R U' R' U R U' R'",
    steps3: "y R' D R U' R' D' R",
    steps4: "U' R U' R' U R' F R F'",
    description: "Edge In Slot",
  },
  {
    alg_id: "F2L_34",
    alg_cat: "F2L",
    algcat_id: 34,
    image: "/alg_images/F2L_34.png",
    steps1: "U R U R' U2 R U R'",
    steps2: "U' R U2 R' U R U R'",
    steps3: "U R' D' R U' R' D R",
    steps4: "y U L' U L U2 L' U L",
    description: "Edge In Slot",
  },
  {
    alg_id: "F2L_35",
    alg_cat: "F2L",
    algcat_id: 35,
    image: "/alg_images/F2L_35.png",
    steps1: "U' R U R' U F' U' F",
    steps2: "U' R U R' d R' U' R",
    steps3: "U2 R U R' F R' F' R",
    steps4: "U2 R U R' y' U' R' U R",
    description: "Edge In Slot",
  },
  {
    alg_id: "F2L_36",
    alg_cat: "F2L",
    algcat_id: 36,
    image: "/alg_images/F2L_36.png",
    steps1: "U F' U' F U' R U R'",
    steps2: "U2 R' F R F' U2 R U R'",
    steps3: "R2 u R U R' U' u' R' U R'",
    steps4: "R U R' U R U R' U' F' U' F",
    description: "Edge In Slot",
  },
  {
    alg_id: "F2L_37",
    alg_cat: "F2L",
    algcat_id: 37,
    image: "/alg_images/F2L_37.png",
    steps1: "R2 U2 F R2 F' U2 R' U R'",
    steps2: "R' F R F' R U' R' U R U' R' U2 R U' R'",
    steps3: "R U R' U2 R U2 R' U y' R' U' R",
    steps4: "R' F R F' R' U2 R2 U R2 U R",
    description: "Pieces in Slot",
  },
  {
    alg_id: "F2L_38",
    alg_cat: "F2L",
    algcat_id: 38,
    image: "/alg_images/F2L_38.png",
    steps1: "R U' R' U' R U R' U2 R U' R'",
    steps2: "R U R' U' R U2 R' U' R U R'",
    steps3: "R2 U2 R' U' R U' R' U2 R'",
    steps4: "R U' R' U' R U R' U' R U2 R'",
    description: "Pieces in Slot",
  },
  {
    alg_id: "F2L_39",
    alg_cat: "F2L",
    algcat_id: 39,
    image: "/alg_images/F2L_39.png",
    steps1: "R U' R' U R U2 R' U R U' R'",
    steps2: "R U2 R U R' U R U2 R2",
    steps3: "R U R' U2 R U' R' U R U R'",
    steps4: "R U2 R' U R U' R' U R U R'",
    description: "Pieces in Slot",
  },
  {
    alg_id: "F2L_40",
    alg_cat: "F2L",
    algcat_id: 40,
    image: "/alg_images/F2L_40.png",
    steps1: "r U' r' U2 r U r' R U R'",
    steps2: "F' L' U2 L F R U R'",
    steps3: "R U' R' U' R U' R' U y' R' U' R",
    steps4: "R U' R' F R U R' U' F' R U' R'",
    description: "Pieces in Slot",
  },
  {
    alg_id: "F2L_41",
    alg_cat: "F2L",
    algcat_id: 41,
    image: "/alg_images/F2L_41.png",
    steps1: "R U' R' r U' r' U2 r U r'",
    steps2: "R U' R' F' L' U2 L F",
    steps3: "R U R' U' y M U' R' F R U M'",
    steps4: "R U R' U' R U' R' U2 y' R' U' R",
    description: "Pieces in Slot",
  },

  // OLL STARTS HERE --------------------------------------------------------------------------------------

  {
    alg_id: "OLL_1",
    alg_cat: "OLL",
    algcat_id: 1,
    image: "/alg_images/OLL_1.png",
    steps1: "(R U2 R') (R' F R F') U2 (R' F R F')",
    steps2: "R U2 R2 F R F' U2 R' F R F'",
    steps3: "y R U' R2 D' r U' r' D R2 U R'",
    steps4: "f R U R' U' R f' U' r' U' R U M'",
    description: "Dot",
  },
  {
    alg_id: "OLL_2",
    alg_cat: "OLL",
    algcat_id: 2,
    image: "/alg_images/OLL_2.png",
    steps1: "F (R U R' U') F' f (R U R' U') f'",
    steps2: "y' R U' R2 D' r U r' D R2 U R'",
    steps3: "F R U R' U' S R U R' U' f'",
    steps4: "F R U R' U' F' f R U R' U' f'",
    description: "Dot",
  },
  {
    alg_id: "OLL_3",
    alg_cat: "OLL",
    algcat_id: 3,
    image: "/alg_images/OLL_3.png",
    steps1: "y' f (R U R' U') f' (U') F (R U R' U') F'",
    steps2: "y R' F2 R2 U2 R' F R U2 R2 F2 R",
    steps3: "y' f R U R' U' f' U' F R U R' U' F'",
    steps4: "r' R2 U R' U r U2 r' U M'",
    description: "Dot",
  },
  {
    alg_id: "OLL_4",
    alg_cat: "OLL",
    algcat_id: 4,
    image: "/alg_images/OLL_4.png",
    steps1: "y' f (R U R' U') f' (U) F (R U R' U') F'",
    steps2: "y' R' F2 R2 U2 R' F' R U2 R2 F2 R",
    steps3: "y' f R U R' U' f' U F R U R' U' F'",
    steps4: "R' F R F' U' S R' U' R U R S'",
    description: "Dot",
  },
  {
    alg_id: "OLL_5",
    alg_cat: "OLL",
    algcat_id: 5,
    image: "/alg_images/OLL_5.png",
    steps1: "r' U2 R U R' U r",
    steps2: "y2 l' U2 L U L' U l",
    steps3: "y2 R' F2 r U r' F R",
    steps4: "y2 R' F R' F' R2 y U' R U' R'",
    description: "square",
  },
  {
    alg_id: "OLL_6",
    alg_cat: "OLL",
    algcat_id: 6,
    image: "/alg_images/OLL_6.png",
    steps1: "r U2 R' U' R U' r'",
    steps2: "F U' R2 D R' U' R D' R2 U F'",
    steps3: "y2 l U2 L' U' L U' l'",
    steps4: "L F2 l' U' l F' L'",
    description: "square",
  },
  {
    alg_id: "OLL_7",
    alg_cat: "OLL",
    algcat_id: 7,
    image: "/alg_images/OLL_7.png",
    steps1: "r U R' U R U2 r'",
    steps2: "L' U2 L U2 L F' L' F",
    steps3: "y2 l U L' U L U2 l'",
    steps4: "r U r' U R U' R' r U' r'",
    description: "Lightning",
  },
  {
    alg_id: "OLL_8",
    alg_cat: "OLL",
    algcat_id: 8,
    image: "/alg_images/OLL_8.png",
    steps1: "y2 r' U' R U' R' U2 r",
    steps2: "l' U' L U' L' U2 l",
    steps3: "R U2 R' U2 R' F R F'",
    steps4: "R' F' r U' r' F2 R",
    description: "Lightning",
  },
  {
    alg_id: "OLL_9",
    alg_cat: "OLL",
    algcat_id: 9,
    image: "/alg_images/OLL_9.png",
    steps1: "y (R U R' U') (R' F R) (R U R' U') F'",
    steps2: "y R U R' U' R' F R2 U R' U' F'",
    steps3: "R U2 R' U' S' R U' R' S",
    steps4: "y2 F' U' F r U' r' U r U r'",
    description: "Fish",
  },
  {
    alg_id: "OLL_10",
    alg_cat: "OLL",
    algcat_id: 10,
    image: "/alg_images/OLL_10.png",
    steps1: "R U R' U R' F R F' R U2 R'",
    steps2: "y F U F' R' F R U' R' F' R",
    steps3: "y M' R' U2 R U R' U R U M",
    steps4: "y2 L' U' L U L F' L2 U' L U F",
    description: "Fish",
  },
  {
    alg_id: "OLL_11",
    alg_cat: "OLL",
    algcat_id: 11,
    image: "/alg_images/OLL_11.png",
    steps1: "M (R U R' U R U2 R') U M'",
    steps2: "r' R2 U R' U R U2 R' U M'",
    steps3: "y2 r U R' U R' F R F' R U2 r'",
    steps4: "M R U R' U R U2 R' U M'",
    description: "Lightning",
  },
  {
    alg_id: "OLL_12",
    alg_cat: "OLL",
    algcat_id: 12,
    image: "/alg_images/OLL_12.png",
    steps1: "y' M' R' U' R U' R' U2 R U' M",
    steps2: "F R U R' U' F' U F R U R' U' F'",
    steps3: "y' S R' U' R U' R' U2 R U2 S'",
    steps4: "y l L2 U' L U' L' U2 L U' M'",
    description: "Lightning",
  },
  {
    alg_id: "OLL_13",
    alg_cat: "OLL",
    algcat_id: 13,
    image: "/alg_images/OLL_13.png",
    steps1: "(r U' r') U' (r U r') (F' U F)",
    steps2: "F U R U2 R' U' R U R' F'",
    steps3: "F U R U' R2 F' R U R U' R'",
    steps4: "r U' r' U' r U r' F' U F",
    description: "Knight",
  },
  {
    alg_id: "OLL_14",
    alg_cat: "OLL",
    algcat_id: 14,
    image: "/alg_images/OLL_14.png",
    steps1: "R' F R U R' F' R F U' F'",
    steps2: "r U R' U' r' F R2 U R' U' F'",
    steps3: "F' U' L' U L2 F L' U' L' U L",
    steps4: "l' U l U l' U' l F U' F'",
    description: "Knight",
  },
  {
    alg_id: "OLL_15",
    alg_cat: "OLL",
    algcat_id: 15,
    image: "/alg_images/OLL_15.png",
    steps1: "r' U' r R' U' R U r' U r",
    steps2: "y2 l' U' l L' U' L U l' U l",
    steps3: "y2 R' F' R L' U' L U R' F R",
    steps4: "r' U' M' U' R U r' U r",
    description: "Knight",
  },
  {
    alg_id: "OLL_16",
    alg_cat: "OLL",
    algcat_id: 16,
    image: "/alg_images/OLL_16.png",
    steps1: "r U r' R U R' U' r U' r'",
    steps2: "r U M U R' U' r U' r'",
    steps3: "y2 R' F R U R' U' F' R U' R' U2 R",
    steps4: "y2 l U l' L U L' U' l U' l'",
    description: "Knight",
  },
  {
    alg_id: "OLL_17",
    alg_cat: "OLL",
    algcat_id: 17,
    image: "/alg_images/OLL_17.png",
    steps1: "R U R' U R' F R F' U2 R' F R F'",
    steps2: "y2 F R' F' R U S' R U' R' S",
    steps3: "y2 F R' F' R2 r' U R U' R' U' M'",
    steps4: "y' F' r U r' U' S r' F r S'",
    description: "Dot",
  },
  {
    alg_id: "OLL_18",
    alg_cat: "OLL",
    algcat_id: 18,
    image: "/alg_images/OLL_18.png",
    steps1: "y (R U2 R') (R' F R F') U2 M' (U R U' r')",
    steps2: "y R U2 R2 F R F' U2 M' U R U' r'",
    steps3: "y F S' R U' R' S R U2 R' U' F'",
    steps4: "r U R' U R U2 r2 U' R U' R' U2 r",
    description: "Dot",
  },
  {
    alg_id: "OLL_19",
    alg_cat: "OLL",
    algcat_id: 19,
    image: "/alg_images/OLL_19.png",
    steps1: "M U (R U R' U') M' (R' F R F')",
    steps2: "y S' R U R' S U' R' F R F'",
    steps3: "M U R U R' U' M' R' F R F'",
    steps4: "R' U2 F R U R' U' F2 U2 F R",
    description: "Dot",
  },
  {
    alg_id: "OLL_20",
    alg_cat: "OLL",
    algcat_id: 20,
    image: "/alg_images/OLL_20.png",
    steps1: "r U R' U' M2 U R U' R' U' M'",
    steps2: "M' U2 M U2 M' U M U2 M' U2 M",
    steps3: "S' R U R' S U' M' U R U' r'",
    steps4: "S R' U' R U R U R U' R' S'",
    description: "Dot",
  },
  {
    alg_id: "OLL_21",
    alg_cat: "OLL",
    algcat_id: 21,
    image: "/alg_images/OLL_21.png",
    steps1: "R U R' U R U' R' U R U2 R'",
    steps2: "y R U2 R' U' R U R' U' R U' R'",
    steps3: "y F R U R' U' R U R' U' R U R' U' F'",
    steps4: "R' U' R U' R' U R U' R' U2 R",
    description: "OCLL",
  },
  {
    alg_id: "OLL_22",
    alg_cat: "OLL",
    algcat_id: 22,
    image: "/alg_images/OLL_22.png",
    steps1: "R U2 (R2' U') (R2 U') (R2' U') U' R",
    steps2: "R U2 R2 U' R2 U' R2 U2 R",
    steps3: "R' U2 R2 U R2 U R2 U2 R'",
    steps4: "f R U R' U' S' R U R' U' F'",
    description: "OCLL",
  },
  {
    alg_id: "OLL_23",
    alg_cat: "OLL",
    algcat_id: 23,
    image: "/alg_images/OLL_23.png",
    steps1: "R2 D R' U2 R D' R' U2 R'",
    steps2: "y2 R2 D' R U2 R' D R U2 R",
    steps3: "R U R' U R U2 R2 U' R U' R' U2 R",
    steps4: "y' R U2 R' U' R U' R' L' U2 L U L' U L",
    description: "OCLL",
  },
  {
    alg_id: "OLL_24",
    alg_cat: "OLL",
    algcat_id: 24,
    image: "/alg_images/OLL_24.png",
    steps1: "r U R' U' r' F R F'",
    steps2: "y' x' R U R' D R U' R' D' x",
    steps3: "L F R' F' L' F R F'",
    steps4: "y R U R D R' U' R D' R2",
    description: "OCLL",
  },
  {
    alg_id: "OLL_25",
    alg_cat: "OLL",
    algcat_id: 25,
    image: "/alg_images/OLL_25.png",
    steps1: "y (F' r U R') (U' r' F R)",
    steps2: "R U2 R D R' U2 R D' R2",
    steps3: "y F' r U R' U' r' F R",
    steps4: "F R' F' r U R U' r'",
    description: "OCLL",
  },
  {
    alg_id: "OLL_26",
    alg_cat: "OLL",
    algcat_id: 26,
    image: "/alg_images/OLL_26.png",
    steps1: "y R U2 R' U' R U' R'",
    steps2: "R' U' R U' R' U2 R",
    steps3: "y2 L' U' L U' L' U2 L",
    steps4: "y2 L' U R U' L U R'",
    description: "OCLL",
  },
  {
    alg_id: "OLL_27",
    alg_cat: "OLL",
    algcat_id: 27,
    image: "/alg_images/OLL_27.png",
    steps1: "R U R' U R U2 R'",
    steps2: "y' R' U2 R U R' U R",
    steps3: "y L' U2 L U L' U L",
    steps4: "y2 L U L' U L U2 L'",
    description: "OCLL",
  },
  {
    alg_id: "OLL_28",
    alg_cat: "OLL",
    algcat_id: 28,
    image: "/alg_images/OLL_28.png",
    steps1: "r U R' U' M U R U' R'",
    steps2: "R' F R S R' F' R S'",
    steps3: "r U R' U' r' R U R U' R'",
    steps4: "y2 M' U M U2 M' U M",
    description: "Corners oriented",
  },
  {
    alg_id: "OLL_29",
    alg_cat: "OLL",
    algcat_id: 29,
    image: "/alg_images/OLL_29.png",
    steps1: "y (R U R') U' (R U' R') (F' U' F) (R U R')",
    steps2: "r2 D' r U r' D r2 U' r' U' r",
    steps3: "y R U R' U' R U' R' F' U' F R U R'",
    steps4: "y S' R U R' U' R' F R F' U S",
    description: "Awkward",
  },
  {
    alg_id: "OLL_30",
    alg_cat: "OLL",
    algcat_id: 30,
    image: "/alg_images/OLL_30.png",
    steps1: "y2 F U (R U2 R') U' (R U2 R') U' F'",
    steps2: "y' r' D' r U' r' D r2 U' r' U r U r'",
    steps3: "y2 F U R U2 R' U' R U2 R' U' F'",
    steps4: "y2 F R' F R2 U' R' U' R U R' F2",
    description: "Awkward",
  },
  {
    alg_id: "OLL_31",
    alg_cat: "OLL",
    algcat_id: 31,
    image: "/alg_images/OLL_31.png",
    steps1: "R' U' F U R U' R' F' R",
    steps2: "y2 S' L' U' L U L F' L' f",
    steps3: "y S R U R' U' f' U' F",
    steps4: "y' F R' F' R U R U R' U' R U' R'",
    description: "P",
  },
  {
    alg_id: "OLL_32",
    alg_cat: "OLL",
    algcat_id: 32,
    image: "/alg_images/OLL_32.png",
    steps1: "S R U R' U' R' F R f'",
    steps2: "y2 L U F' U' L' U L F L'",
    steps3: "R U B' U' R' U R B R'",
    steps4: "y' R' F R F' U' r U' r' U r U r'",
    description: "P",
  },
  {
    alg_id: "OLL_33",
    alg_cat: "OLL",
    algcat_id: 33,
    image: "/alg_images/OLL_33.png",
    steps1: "R U R' U' R' F R F'",
    steps2: "y2 L' U' L U L F' L' F",
    steps3: "y2 r' F' r U r U' r' F",
    steps4: "R U R' F' U' F R U' R'",
    description: "T",
  },
  {
    alg_id: "OLL_34",
    alg_cat: "OLL",
    algcat_id: 34,
    image: "/alg_images/OLL_34.png",
    steps1: "y2 R U R2 U' R' F (R U R U') F'",
    steps2: "y f R f' U' r' U' R U M'",
    steps3: "y2 R U R2 U' R' F R U R U' F'",
    steps4: "F R U R' U' R' F' r U R U' r'",
    description: "Fish",
  },
  {
    alg_id: "OLL_35",
    alg_cat: "OLL",
    algcat_id: 35,
    image: "/alg_images/OLL_35.png",
    steps1: "(R U2 R') (R' F R F') (R U2 R')",
    steps2: "R U2 R2 F R F' R U2 R'",
    steps3: "f R U R' U' f' R U R' U R U2 R'",
    steps4: "y2 R2 F R F' R U2 R' U R U2 R' U' R",
    description: "W",
  },
  {
    alg_id: "OLL_36",
    alg_cat: "OLL",
    algcat_id: 36,
    image: "/alg_images/OLL_36.png",
    steps1: "y2 L' U' L U' L' U L U L F' L' F",
    steps2: "y R U R2 F' U' F U R2 U2 R'",
    steps3: "y2 R U R' F' R U R' U' R' F R U' R' F R F'",
    steps4: "y2 R' F' U' F2 U R U' R' F' R",
    description: "W",
  },
  {
    alg_id: "OLL_37",
    alg_cat: "OLL",
    algcat_id: 37,
    image: "/alg_images/OLL_37.png",
    steps1: "F R (U' R' U') (R U R') F'",
    steps2: "F R' F' R U R U' R'",
    steps3: "F R U' R' U' R U R' F'",
    steps4: "y F' r U r' U' r' F r",
    description: "Fish",
  },
  {
    alg_id: "OLL_38",
    alg_cat: "OLL",
    algcat_id: 38,
    image: "/alg_images/OLL_38.png",
    steps1: "R U R' U R U' R' U' R' F R F'",
    steps2: "y F R U' R' S U' R U R' f'",
    steps3: "y2 L' U2 l' D' l U2 l' D l L",
    steps4: "R' U2 r' D' r U2 r' D R r",
    description: "W",
  },
  {
    alg_id: "OLL_39",
    alg_cat: "OLL",
    algcat_id: 39,
    image: "/alg_images/OLL_39.png",
    steps1: "y L F' (L' U' L U) F U' L'",
    steps2: "y' f' r U r' U' r' F r S",
    steps3: "y' R U R' F' U' F U R U2 R'",
    steps4: "y L F' L' U' L U F U' L'",
    description: "Lightning",
  },
  {
    alg_id: "OLL_40",
    alg_cat: "OLL",
    algcat_id: 40,
    image: "/alg_images/OLL_40.png",
    steps1: "y R' F R U R' U' F' U R",
    steps2: "y' f R' F' R U R U' R' S'",
    steps3: "R r D r' U r D' r' U' R'",
    steps4: "y' L' U' L F U F' U' L' U2 L",
    description: "Lightning",
  },
  {
    alg_id: "OLL_41",
    alg_cat: "OLL",
    algcat_id: 41,
    image: "/alg_images/OLL_41.png",
    steps1: "y2 R U R' U R U2 R' F R U R' U' F'",
    steps2: "y2 F U R2 D R' U' R D' R2 F'",
    steps3: "y' S U' R' F' U' F U R S'",
    steps4: "M U' F' L' U' L U F M'",
    description: "Awkward",
  },
  {
    alg_id: "OLL_42",
    alg_cat: "OLL",
    algcat_id: 42,
    image: "/alg_images/OLL_42.png",
    steps1: "R' U' R U' R' U2 R F R U R' U' F'",
    steps2: "y F S' R U R' U' F' U S",
    steps3: "y R' F R F' R' F R F' R U R' U' R U R'",
    steps4: "y R' U' F2 u' R U R' D R2 B",
    description: "Awkward",
  },
  {
    alg_id: "OLL_43",
    alg_cat: "OLL",
    algcat_id: 43,
    image: "/alg_images/OLL_43.png",
    steps1: "y R' U' F' U F R",
    steps2: "y2 F' U' L' U L F",
    steps3: "f' L' U' L U f",
    steps4: "B' U' R' U R B",
    description: "P",
  },
  {
    alg_id: "OLL_44",
    alg_cat: "OLL",
    algcat_id: 44,
    image: "/alg_images/OLL_44.png",
    steps1: "f R U R' U' f'",
    steps2: "y2 F U R U' R' F'",
    steps3: "y R U B U' B' R'",
    steps4: "y' L U F U' F' L'",
    description: "P",
  },
  {
    alg_id: "OLL_45",
    alg_cat: "OLL",
    algcat_id: 45,
    image: "/alg_images/OLL_45.png",
    steps1: "F R U R' U' F'",
    steps2: "y R' F' U' F U R",
    steps3: "y2 f U R U' R' f'",
    steps4: "y2 F' L' U' L U F",
    description: "T",
  },
  {
    alg_id: "OLL_46",
    alg_cat: "OLL",
    algcat_id: 46,
    image: "/alg_images/OLL_46.png",
    steps1: "R' U' R' F R F' U R",
    steps2: "R' F' U' F R U' R' U2 R",
    steps3: "y F R U R' U' F' U' R U R' U R U2 R'",
    steps4: "l' U2 L2 F' L' F U L' U l",
    description: "C",
  },
  {
    alg_id: "OLL_47",
    alg_cat: "OLL",
    algcat_id: 47,
    image: "/alg_images/OLL_47.png",
    steps1: "F' (L' U' L U) (L' U' L U) F",
    steps2: "y' F R' F' R U2 R U' R' U R U2 R'",
    steps3: "F' L' U' L U L' U' L U F",
    steps4: "R' U' R' F R F' R' F R F' U R",
    description: "L",
  },
  {
    alg_id: "OLL_48",
    alg_cat: "OLL",
    algcat_id: 48,
    image: "/alg_images/OLL_48.png",
    steps1: "F R U R' U' R U R' U' F'",
    steps2: "y2 f U R U' R' U R U' R' f'",
    steps3: "R U2 R' U' R U R' U2 R' F R F'",
    steps4: "F R' F' U2 R U R' U R2 U2 R'",
    description: "L",
  },
  {
    alg_id: "OLL_49",
    alg_cat: "OLL",
    algcat_id: 49,
    image: "/alg_images/OLL_49.png",
    steps1: "y2 r U' r2 U r2 U r2 U' r",
    steps2: "l U' l2 U l2 U l2 U' l",
    steps3: "R B' R2 F R2 B R2 F' R",
    steps4: "y2 R' F R' F' R2 U2 B' R B R'",
    description: "L",
  },
  {
    alg_id: "OLL_50",
    alg_cat: "OLL",
    algcat_id: 50,
    image: "/alg_images/OLL_50.png",
    steps1: "r' U r2 U' r2 U' r2 U r'",
    steps2: "y2 R' F R2 B' R2 F' R2 B R'",
    steps3: "y' R U2 R' U' R U' R' F R U R' U' F'",
    steps4: "y2 l' U l2 U' l2 U' l2 U l'",
    description: "L",
  },
  {
    alg_id: "OLL_51",
    alg_cat: "OLL",
    algcat_id: 51,
    image: "/alg_images/OLL_51.png",
    steps1: "f (R U R' U') (R U R' U') f'",
    steps2: "y2 F U R U' R' U R U' R' F'",
    steps3: "f R U R' U' R U R' U' f'",
    steps4: "y' R' U' R' F R F' R U' R' U2 R",
    description: "Line",
  },
  {
    alg_id: "OLL_52",
    alg_cat: "OLL",
    algcat_id: 52,
    image: "/alg_images/OLL_52.png",
    steps1: "y2 R' F' U' F U' R U R' U R",
    steps2: "R U R' U R U' B U' B' R'",
    steps3: "R U R' U R d' R U' R' F'",
    steps4: "R U R' U R U' y R U' R' F'",
    description: "Line",
  },
  {
    alg_id: "OLL_53",
    alg_cat: "OLL",
    algcat_id: 53,
    image: "/alg_images/OLL_53.png",
    steps1: "r' U' R U' R' U R U' R' U2 r",
    steps2: "y2 l' U' L U' L' U L U' L' U2 l",
    steps3: "y r' U2 R U R' U' R U R' U r",
    steps4: "y' l' U2 L U L' U' L U L' U l",
    description: "L",
  },
  {
    alg_id: "OLL_54",
    alg_cat: "OLL",
    algcat_id: 54,
    image: "/alg_images/OLL_54.png",
    steps1: "r U R' U R U' R' U R U2 r'",
    steps2: "y' r U2 R' U' R U R' U' R U' r'",
    steps3: "y2 l U L' U L U' L' U L U2 l'",
    steps4: "y' r U r' R U R' U' R U R' U' r U' r'",
    description: "L",
  },
  {
    alg_id: "OLL_55",
    alg_cat: "OLL",
    algcat_id: 55,
    image: "/alg_images/OLL_55.png",
    steps1: "R U2 R2 (U' R U' R') U2 (F R F')",
    steps2: "y R' F U R U' R2 F' R2 U R' U' R",
    steps3: "y R' F R U R U' R2 F' R2 U' R' U R U R'",
    steps4: "R U2 R2 U' R U' R' U2 F R F'",
    description: "Line",
  },
  {
    alg_id: "OLL_56",
    alg_cat: "OLL",
    algcat_id: 56,
    image: "/alg_images/OLL_56.png",
    steps1: "r U r' U R U' R' U R U' R' r U' r'",
    steps2: "r U r' U R U' R' M' U R U2 r'",
    steps3: "F R U R' U' R F' r U R' U' r'",
    steps4: "r' U' r U' R' U R U' R' U R r' U r",
    description: "Line",
  },
  {
    alg_id: "OLL_57",
    alg_cat: "OLL",
    algcat_id: 57,
    image: "/alg_images/OLL_57.png",
    steps1: "R U R' U' M' U R U' r'",
    steps2: "y R U' R' S' R U R' S",
    steps3: "y R U R' S' R U' R' S",
    steps4: "R U R' U' R' r U R U' r'",
    description: "Corners oriented",
  },

  // PLL STARTS HERE --------------------------------------------------------------------------------------

  {
    alg_id: "PLL_1",
    alg_cat: "PLL",
    algcat_id: 1,
    image: "/alg_images/PLL_1.png",
    steps1: "x R' U R' D2 R U' R' D2 R2 x'",
    steps2: "y' x L2 D2 L' U' L D2 L' U L'",
    steps3: "l' U R' D2 R U' R' D2 R2 x'",
    steps4: "y x' R2 D2 R' U' R D2 R' U R' x",
    description: "Aa perm",
  },
  {
    alg_id: "PLL_2",
    alg_cat: "PLL",
    algcat_id: 2,
    image: "/alg_images/PLL_2.png",
    steps1: "x R2 D2 R U R' D2 R U' R x'",
    steps2: "y' x L U' L D2 L' U L D2 L2",
    steps3: "y x' R U' R D2 R' U R D2 R2 x",
    steps4: "y2 x' L2 D2 L U L' D2 L U' L",
    description: "Ab perm",
  },
  {
    alg_id: "PLL_3",
    alg_cat: "PLL",
    algcat_id: 3,
    image: "/alg_images/PLL_3.png",
    steps1: "y x' R U' R' D R U R' D' R U R' D R U' R' D' x",
    steps2: "y R' U' R' D' R U' R' D R U R' D' R U R' D R2",
    steps3: "R2 U F' R' U R U' R' U R U' R' U R U' F U' R2",
    steps4: "y x' L' U L D' L' U' L D L' U' L D' L' U L D",
    description: "E perm",
  },
  {
    alg_id: "PLL_4",
    alg_cat: "PLL",
    algcat_id: 4,
    image: "/alg_images/PLL_4.png",
    steps1: "y R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    steps2: "R' U R U' R2 F' U' F U R F R' F' R2",
    steps3: "y R' F R f' R' F R2 U R' U' R' F' R2 U R' S",
    steps4: "y R2 F R F' R' U' F' U F R2 U R' U' R",
    description: "F perm",
  },
  {
    alg_id: "PLL_5",
    alg_cat: "PLL",
    algcat_id: 5,
    image: "/alg_images/PLL_5.png",
    steps1: "R2 U R' U R' U' R U' R2 D U' R' U R D'",
    steps2: "R2 u R' U R' U' R u' R2 F' U F",
    steps3: "R2 u R' U R' U' R u' R2 y' R' U R",
    steps4: "y R U R' F' R U R' U' R' F R U' R' F R2 U' R' U' R U R' F'",
    description: "Ga perm",
  },
  {
    alg_id: "PLL_6",
    alg_cat: "PLL",
    algcat_id: 6,
    image: "/alg_images/PLL_6.png",
    steps1: "(R' U' R U) D' R2 (U R' U R U' R U') R2 D",
    steps2: "D R' U' R U D' R2 U R' U R U' R U' R2",
    steps3: "R' U' R U D' R2 U R' U R U' R U' R2 D",
    steps4: "y F' U' F R2 u R' U R U' R u' R2",
    description: "Gb perm",
  },
  {
    alg_id: "PLL_7",
    alg_cat: "PLL",
    algcat_id: 7,
    image: "/alg_images/PLL_7.png",
    steps1: "R2 (U' R U' R U R' U) R2 D' (U R U' R') D",
    steps2: "D R2 U' R U' R U R' U R2 D' U R U' R'",
    steps3: "R2 U' R U' R U R' U R2 D' U R U' R' D",
    steps4: "y2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2",
    description: "Gc perm",
  },
  {
    alg_id: "PLL_8",
    alg_cat: "PLL",
    algcat_id: 8,
    image: "/alg_images/PLL_8.png",
    steps1: "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    steps2: "D' R U R' U' D R2 U' R U' R' U R' U R2",
    steps3: "R U R' y' R2 u' R U' R' U R' u R2",
    steps4: "y R2 F' R U R U' R' F' R U2 R' U2 R' F2 R2",
    description: "Gd perm",
  },
  {
    alg_id: "PLL_9",
    alg_cat: "PLL",
    algcat_id: 9,
    image: "/alg_images/PLL_9.png",
    steps1: "M2 U' M2 U2 M2 U' M2",
    steps2: "M2 U M2 U2 M2 U M2",
    steps3: "R2 S2 R2 U' R2 S2 R2",
    steps4: "M2 U2 M2 U M2 U2 M2",
    description: "H perm",
  },
  {
    alg_id: "PLL_10",
    alg_cat: "PLL",
    algcat_id: 10,
    image: "/alg_images/PLL_10.png",
    steps1: "y (R' U L') U2 (R U' R') U2 R L",
    steps2: "y2 x R2 F R F' R U2 r' U r U2 x'",
    steps3: "y R' U L' U2 R U' R' U2 R L",
    steps4: "L' U' L F L' U' L U L F' L2 U L",
    description: "Ja perm",
  },
  {
    alg_id: "PLL_11",
    alg_cat: "PLL",
    algcat_id: 11,
    image: "/alg_images/PLL_11.png",
    steps1: "R U R' F' R U R' U' R' F R2 U' R'",
    steps2: "R U2 R' U' R U2 L' U R' U' L",
    steps3: "r' F R F' r U2 R' U R U2 R'",
    steps4: "L' U R U' L U2 R' U R U2 R'",
    description: "Jb perm",
  },
  {
    alg_id: "PLL_12",
    alg_cat: "PLL",
    algcat_id: 12,
    image: "/alg_images/PLL_12.png",
    steps1: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    steps2: "F' R U R' U' R' F R2 F U' R' U' R U F' R'",
    steps3: "R F U' R' U R U F' R2 F' R U R U' R' F",
    steps4: "r' D r U2 r' D r U2 r' D r U2 r' D r U2 r' D r",
    description: "Na perm",
  },
  {
    alg_id: "PLL_13",
    alg_cat: "PLL",
    algcat_id: 13,
    image: "/alg_images/PLL_13.png",
    steps1: "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    steps2: "r' D' F r U' r' F' D r2 U r' U' r' F r F'",
    steps3: "R' U L' U2 R U' L R' U L' U2 R U' L",
    steps4: "R' U R U' R' F' U' F R U R' U' R U' f R f'",
    description: "Nb perm",
  },
  {
    alg_id: "PLL_14",
    alg_cat: "PLL",
    algcat_id: 14,
    image: "/alg_images/PLL_14.png",
    steps1: "y R U' R' U' R U R D R' U' R D' R' U2 R'",
    steps2: "y R U R' F' R U2 R' U2 R' F R U R U2 R'",
    steps3: "L U2 L' U2 L F' L' U' L U L F L2",
    steps4: "y R U' R' U' R U R' U R' D' R U' R' D R2 U R'",
    description: "Ra perm",
  },
  {
    alg_id: "PLL_15",
    alg_cat: "PLL",
    algcat_id: 15,
    image: "/alg_images/PLL_15.png",
    steps1: "R' U2 R U2 R' F R U R' U' R' F' R2",
    steps2: "y R2 F R U R U' R' F' R U2 R' U2 R",
    steps3: "R' U2 R' D' R U' R' D R U R U' R' U' R",
    steps4: "y R' U R U R' U' R' D' R U R' D R U2 R",
    description: "Rb perm",
  },
  {
    alg_id: "PLL_16",
    alg_cat: "PLL",
    algcat_id: 16,
    image: "/alg_images/PLL_16.png",
    steps1: "R U R' U' R' F R2 U' R' U' R U R' F'",
    steps2: "R U R' U' R' F R2 U' R' U F' L' U L",
    steps3: "R2 u R2 u' R2 F2 u' F2 u F2",
    steps4: "l b d' L' U' F U2 L' U' L' U L U' f' S M r u E U' R'",
    description: "T perm",
  },
  {
    alg_id: "PLL_17",
    alg_cat: "PLL",
    algcat_id: 17,
    image: "/alg_images/PLL_17.png",
    steps1: "y2 M2 U M U2 M' U M2",
    steps2: "R U R' U R' U' R2 U' R' U R' U R",
    steps3: "y R2 U' S' U2 S U' R2",
    steps4: "y2 R U' R U R U R U' R' U' R2",
    description: "Ua perm",
  },
  {
    alg_id: "PLL_18",
    alg_cat: "PLL",
    algcat_id: 18,
    image: "/alg_images/PLL_18.png",
    steps1: "y2 M2 U' M U2 M' U' M2",
    steps2: "R2' U R U R' U' R3 U' R' U R'",
    steps3: "R' U R' U' R' U' R' U R U R2",
    steps4: "y2 R2 U R U R' U' R' U' R' U R'",
    description: "Ub perm",
  },
  {
    alg_id: "PLL_19",
    alg_cat: "PLL",
    algcat_id: 19,
    image: "/alg_images/PLL_19.png",
    steps1: "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2",
    steps2: "R' U R U' R' f' U' R U2 R' U' R U' R' f R",
    steps3: "R' U R' U' y R' F' R2 U' R' U R' F R F",
    steps4: "y R U' R U R' D R D' R U' D R2 U R2 D' R2",
    description: "V perm",
  },
  {
    alg_id: "PLL_20",
    alg_cat: "PLL",
    algcat_id: 20,
    image: "/alg_images/PLL_20.png",
    steps1: "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    steps2: "F R' F R2 U' R' U' R U R' F' R U R' U' F'",
    steps3: "R2 U' R2 U' R2 U F U F' R2 F U' F'",
    steps4: "F R' F' R U R U' R2 U' R U R f' U' f",
    description: "Y perm",
  },
  {
    alg_id: "PLL_21",
    alg_cat: "PLL",
    algcat_id: 21,
    image: "/alg_images/PLL_21.png",
    steps1: "(M2 U) (M2 U) (M' U2) M2 (U2 M')",
    steps2: "M' U' M2 U' M2 U' M' U2 M2",
    steps3: "M2 U M2 U M' U2 M2 U2 M'",
    steps4: "y M2 U' M2 U' M' U2 M2 U2 M'",
    description: "Z perm",
  },
];
